## **Hypothesis Testing**

In [1]:
#packages
import pandas as pd
import numpy as np
from scipy import stats
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
import scipy
scipy.__version__

'1.7.3'

## **Chi-Square Test-**
The test is applied when you have two categorical variables from a single population. It is used to determine whether there is a significant association between the two categorical variables.


In [3]:
import scipy.stats as stats
import seaborn as sns
dataset=sns.load_dataset('tips')
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)
# crosstab shows the data in a matrix format

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [5]:
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [6]:
dataset_table.values 


array([[60, 97],
       [33, 54]])

In [7]:
#Observed Values
Observed_Values = dataset_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[60 97]
 [33 54]]


In [8]:
val=stats.chi2_contingency(dataset_table)
val
#here inside the brackets we have expected values 

(0.0, 1.0, 1, array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [9]:
val[1]

1.0

In [10]:
val[3]

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [11]:
Expected_Values=val[3]
Expected_Values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [12]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_rows
#this shows the number of rows in the matrix dataset_table

2

In [13]:
no_of_columns=len(dataset_table.iloc[0,0:2])
no_of_columns
#this shows the number of columns in the matrix dataset_table

2

In [14]:
ddof=(no_of_rows-1)*(no_of_columns-1)
ddof
#calculating degrees of freedom

1

In [15]:
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [16]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
#in this equation the observed values and expected values are zipping here.
#zipping, because the observed and and expected values are now in a 2*2 matrix format

In [17]:
chi_square
#after doing the chisq equation using 2*2 matrix we will again get a 2 rows 
#thise 2 rows are adding up to get the chi_sq_statistic

array([0.00119737, 0.00073745])

In [18]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 0.001934818536627623


In [19]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)
#ppf is percent point function, it is the inverse of cdf(cumulative density fuction)
#here we need to assign a p and q value. 
#p value is alpha, q=1-p = 1-alpha

critical_value: 3.841458820694124


from chi -square statistic and critical value we can find solution for the test\
if chi_square_statistic >= critical_value we Reject Ho and\
chi_square_statistic < critical_value we Accept Ho  

In [20]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)
#for calculating chisq we use chisq.cdf, just opposite of ppf, cdf=cumulative density function


p-value: 0.964915107315732
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.964915107315732


**In P value method**\
If P value > 0.05 (significance value), Accept Ho\
P Value < 0.05 (significance value), Reject Ho

**In critical value method**\
Test statistic value > critical value, Reject Ho\
Test statistic value < critical value, Accept Ho

**By P value method**\
Ho =  There is No relationship between 2 categorical variables\
H1 = There is a relationshio between 2 categorical variables

**By critical value method**\
Ho =  There is No relationship between 2 categorical variables\
H1 = There is a relationshio between 2 categorical variables



In [21]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables
Retain H0,There is no relationship between 2 categorical variables
